services:
  fe:
    build:
      context: ./fe
      dockerfile: Dockerfile
      args:
        - VITE_GOOGLE_CLIENT_ID=${VITE_GOOGLE_CLIENT_ID}
    container_name: luminaprep-fe
    ports:
      - ${FE_PORT_EXPOSE}:${FE_PORT}
    environment:
      - NODE_ENV=${NODE_ENV}
      - PORT=${FE_PORT}
      - API_URL=${API_URL}
    depends_on:
      - api
    restart: unless-stopped
    networks:
      - luminaprep-net

  redis:
    image: redis:7-alpine
    container_name: luminaprep-redis
    restart: always
    command: --maxmemory-policy noeviction
    networks:
      - luminaprep-net

  api:
    build:
      context: ./backend
      dockerfile: Dockerfile
    image: luminaprep-backend:latest
    container_name: luminaprep-api
    ports:
      - ${API_PORT_EXPOSE}:${API_PORT}
    env_file:
      - ./backend/.env
    environment:
      - TZ=Asia/Jakarta
      - LANGFUSE_PUBLIC_KEY=${LANGFUSE_PUBLIC_KEY}
      - LANGFUSE_SECRET_KEY=${LANGFUSE_SECRET_KEY}
      - LANGFUSE_HOST=${LANGFUSE_HOST}
      - LANGFUSE_ENABLED=${LANGFUSE_ENABLED}
    depends_on:
      - redis
    restart: unless-stopped
    networks:
      - luminaprep-net
    volumes:
      - ./backend/chroma_db:/app/chroma_db
      - ./backend/uploads:/app/uploads

  celery_worker:
    image: luminaprep-backend:latest
    container_name: luminaprep-celery-worker
    command: uv run celery -A app.celery_app worker --loglevel=info
    env_file:
      - ./backend/.env
    environment:
      - TZ=Asia/Jakarta
      - LANGFUSE_PUBLIC_KEY=${LANGFUSE_PUBLIC_KEY}
      - LANGFUSE_SECRET_KEY=${LANGFUSE_SECRET_KEY}
      - LANGFUSE_HOST=${LANGFUSE_HOST}
      - LANGFUSE_ENABLED=${LANGFUSE_ENABLED}
    depends_on:
      - redis
    restart: unless-stopped
    networks:
      - luminaprep-net
    volumes:
      - ./backend/chroma_db:/app/chroma_db
      - ./backend/uploads:/app/uploads

  db:
    image: mysql:8.4
    container_name: luminaprep-mysql
    restart: always
    environment:
      TZ: Asia/Jakarta
      MYSQL_ROOT_PASSWORD: ${MYSQL_PASS_ROOT}
      MYSQL_DATABASE: ${MYSQL_DB}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASS}
    ports:
      - "${MYSQL_PORT_EXPOSE}:${MYSQL_PORT}"
    volumes:
      - ./dbdata:/var/lib/mysql
    networks:
      - luminaprep-net

  phpmyadmin:
    image: phpmyadmin:latest
    container_name: luminaprep-phpmyadmin
    restart: always
    ports:
      - "${PMA_PORT_EXPOSE}:${PMA_PORT}"
    environment:
      PMA_HOST: db
    depends_on:
      - db
    networks:
      - luminaprep-net

networks:
  luminaprep-net:
    driver: bridge
