"""Add soft delete fields and avatar_url to user table

Revision ID: 00b0dac44154
Revises: 5e22f1df1ecc
Create Date: 2026-05-10 08:14:23.369000

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '00b0dac44154'
down_revision: Union[str, Sequence[str], None] = '5e22f1df1ecc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    
    # Check and add columns to existing tables safely
    connection = op.get_bind()
    inspector = sa.inspect(connection)
    
    # Helper function to check if column exists
    def column_exists(table_name, column_name):
        if table_name in inspector.get_table_names():
            columns = [col['name'] for col in inspector.get_columns(table_name)]
            return column_name in columns
        return False
    
    # Add avatar_url to users table if table exists
    if inspector.has_table("users"):
        if not column_exists("users", "avatar_url"):
            op.execute("ALTER TABLE users ADD COLUMN avatar_url TEXT COMMENT 'User avatar URL'")
        
        if not column_exists("users", "deleted_at"):
            op.execute("ALTER TABLE users ADD COLUMN deleted_at DATETIME COMMENT 'Soft delete timestamp'")
    
    # Add deleted_at to other tables if they exist
    tables_to_update = ["projects", "materials", "quizzes", "questions", "user_attempts", "agent_metrics"]
    
    for table_name in tables_to_update:
        if inspector.has_table(table_name) and not column_exists(table_name, "deleted_at"):
            op.execute(f"ALTER TABLE {table_name} ADD COLUMN deleted_at DATETIME COMMENT 'Soft delete timestamp'")
    
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    
    # Batch operations for better compatibility
    with op.batch_alter_table("users") as batch_op:
        batch_op.drop_column('avatar_url')
        batch_op.drop_column('deleted_at')
    
    with op.batch_alter_table("projects") as batch_op:
        batch_op.drop_column('deleted_at')
    
    with op.batch_alter_table("materials") as batch_op:
        batch_op.drop_column('deleted_at')
    
    with op.batch_alter_table("quizzes") as batch_op:
        batch_op.drop_column('deleted_at')
    
    with op.batch_alter_table("questions") as batch_op:
        batch_op.drop_column('deleted_at')
    
    with op.batch_alter_table("user_attempts") as batch_op:
        batch_op.drop_column('deleted_at')
    
    with op.batch_alter_table("agent_metrics") as batch_op:
        batch_op.drop_column('deleted_at')
    
    # ### end Alembic commands ###
