"""add quiz_sessions table and update user_attempts

Revision ID: 0fb0ed43336d
Revises: 5188197b8b59
Create Date: 2026-05-11 10:26:42.949111

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '0fb0ed43336d'
down_revision: Union[str, Sequence[str], None] = '5188197b8b59'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    
    # Check if quiz_sessions table exists before creating
    conn = op.get_bind()
    inspector = sa.inspect(conn)
    tables = inspector.get_table_names()
    
    if 'quiz_sessions' not in tables:
        op.create_table('quiz_sessions',
        sa.Column('score', mysql.FLOAT(), nullable=True, comment='Quiz session score'),
        sa.Column('total_questions', mysql.INTEGER(), nullable=True, comment='Total questions in quiz'),
        sa.Column('correct_answers', mysql.INTEGER(), nullable=True, comment='Number of correct answers'),
        sa.Column('status', mysql.VARCHAR(length=50), nullable=True, comment='Quiz session status'),
        sa.Column('id', mysql.VARCHAR(length=36), nullable=False, comment='Quiz session ID'),
        sa.Column('user_id', mysql.VARCHAR(length=36), nullable=False, comment='User ID'),
        sa.Column('quiz_id', mysql.VARCHAR(length=36), nullable=False, comment='Quiz ID'),
        sa.Column('started_at', mysql.DATETIME(), nullable=False, comment='Session started at'),
        sa.Column('completed_at', mysql.DATETIME(), nullable=True, comment='Session completed at'),
        sa.Column('deleted_at', mysql.DATETIME(), nullable=True, comment='Soft delete timestamp'),
        sa.ForeignKeyConstraint(['quiz_id'], ['quizzes.id'], name=op.f('quiz_sessions_ibfk_1')),
        sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('quiz_sessions_ibfk_2')),
        sa.PrimaryKeyConstraint('id'),
        mysql_collate='utf8mb4_0900_ai_ci',
        mysql_default_charset='utf8mb4',
        mysql_engine='InnoDB'
        )
    
    # Add quiz_session_id column to user_attempts if it doesn't exist
    if 'user_attempts' in tables:
        columns = [col['name'] for col in inspector.get_columns('user_attempts')]
        if 'quiz_session_id' not in columns:
            op.add_column('user_attempts', sa.Column('quiz_session_id', mysql.VARCHAR(length=36), nullable=True, comment='Quiz session ID'))
            # Add foreign key constraint
            op.create_foreign_key('user_attempts_ibfk_4', 'user_attempts', 'quiz_sessions', ['quiz_session_id'], ['id'])
    
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    
    # Remove foreign key constraint first
    conn = op.get_bind()
    inspector = sa.inspect(conn)
    
    if 'user_attempts' in inspector.get_table_names():
        try:
            op.drop_constraint('user_attempts_ibfk_4', 'user_attempts', type_='foreignkey')
        except:
            pass  # Constraint might not exist
        
        # Remove quiz_session_id column if it exists
        columns = [col['name'] for col in inspector.get_columns('user_attempts')]
        if 'quiz_session_id' in columns:
            op.drop_column('user_attempts', 'quiz_session_id')
    
    # Drop quiz_sessions table if it exists
    if 'quiz_sessions' in inspector.get_table_names():
        op.drop_table('quiz_sessions')
    
    # ### end Alembic commands ###
