"""Create all tables

Revision ID: 5188197b8b59
Revises: 00b0dac44154
Create Date: 2026-05-10 09:22:09.438308

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5188197b8b59'
down_revision: Union[str, Sequence[str], None] = '00b0dac44154'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    
    # Create users table
    op.create_table('users',
        sa.Column('email', sa.String(length=255), nullable=False, comment='User email'),
        sa.Column('hashed_password', sa.String(length=255), nullable=False, comment='User hashed password'),
        sa.Column('full_name', sa.String(length=255), nullable=True, comment='User full name'),
        sa.Column('avatar_url', sa.TEXT(), nullable=True, comment='User avatar URL'),
        sa.Column('id', sa.String(length=36), nullable=False, comment='User ID'),
        sa.Column('created_at', sa.DateTime(), nullable=False, comment='User created at'),
        sa.Column('updated_at', sa.DateTime(), nullable=False, comment='User updated at'),
        sa.Column('deleted_at', sa.DateTime(), nullable=True, comment='Soft delete timestamp'),
        sa.PrimaryKeyConstraint('id'),
        sa.UniqueConstraint('email')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=False)
    
    # Create projects table
    op.create_table('projects',
        sa.Column('title', sa.String(length=255), nullable=False, comment='Project title'),
        sa.Column('description', sa.String(length=1000), nullable=True, comment='Project description'),
        sa.Column('vector_collection_name', sa.String(length=255), nullable=True, comment='Vector collection name'),
        sa.Column('status', sa.String(length=50), nullable=False, comment='Project status'),
        sa.Column('id', sa.String(length=36), nullable=False, comment='Project ID'),
        sa.Column('user_id', sa.String(length=36), nullable=False, comment='User ID'),
        sa.Column('created_at', sa.DateTime(), nullable=False, comment='Project created at'),
        sa.Column('updated_at', sa.DateTime(), nullable=False, comment='Project updated at'),
        sa.Column('deleted_at', sa.DateTime(), nullable=True, comment='Soft delete timestamp'),
        sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
        sa.PrimaryKeyConstraint('id')
    )
    
    # Create materials table
    op.create_table('materials',
        sa.Column('file_name', sa.String(length=255), nullable=False, comment='Material file name'),
        sa.Column('file_type', sa.String(length=50), nullable=False, comment='Material file type'),
        sa.Column('storage_path', sa.String(length=512), nullable=False, comment='Material storage path'),
        sa.Column('status', sa.String(length=50), nullable=False, comment='Material status'),
        sa.Column('summary', sa.String(length=2000), nullable=True, comment='Material summary'),
        sa.Column('citations', sa.String(length=2000), nullable=True, comment='Material citations'),
        sa.Column('id', sa.String(length=36), nullable=False, comment='Material ID'),
        sa.Column('project_id', sa.String(length=36), nullable=False, comment='Project ID'),
        sa.Column('user_id', sa.String(length=36), nullable=False, comment='User ID'),
        sa.Column('created_at', sa.DateTime(), nullable=False, comment='Material created at'),
        sa.Column('updated_at', sa.DateTime(), nullable=False, comment='Material updated at'),
        sa.Column('deleted_at', sa.DateTime(), nullable=True, comment='Soft delete timestamp'),
        sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
        sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
        sa.PrimaryKeyConstraint('id')
    )
    
    # Create quizzes table
    op.create_table('quizzes',
        sa.Column('difficulty_level', sa.String(length=50), nullable=False, comment='Quiz difficulty level'),
        sa.Column('question_count', sa.Integer(), nullable=False, comment='Quiz question count'),
        sa.Column('status', sa.String(length=50), nullable=False, comment='Quiz status'),
        sa.Column('id', sa.String(length=36), nullable=False, comment='Quiz ID'),
        sa.Column('project_id', sa.String(length=36), nullable=False, comment='Project ID'),
        sa.Column('created_at', sa.DateTime(), nullable=False, comment='Quiz created at'),
        sa.Column('updated_at', sa.DateTime(), nullable=False, comment='Quiz updated at'),
        sa.Column('deleted_at', sa.DateTime(), nullable=True, comment='Soft delete timestamp'),
        sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
        sa.PrimaryKeyConstraint('id')
    )
    
    # Create questions table
    op.create_table('questions',
        sa.Column('question_text', sa.String(length=2000), nullable=False, comment='Question text'),
        sa.Column('correct_answer', sa.String(length=1000), nullable=False, comment='Correct answer'),
        sa.Column('explanation', sa.String(length=2000), nullable=True, comment='Question explanation'),
        sa.Column('id', sa.String(length=36), nullable=False, comment='Question ID'),
        sa.Column('quiz_id', sa.String(length=36), nullable=False, comment='Quiz ID'),
        sa.Column('options', sa.JSON(), nullable=False, comment='Question options'),
        sa.Column('question_metadata', sa.JSON(), nullable=True, comment='Question metadata'),
        sa.Column('created_at', sa.DateTime(), nullable=False, comment='Question created at'),
        sa.Column('updated_at', sa.DateTime(), nullable=False, comment='Question updated at'),
        sa.Column('deleted_at', sa.DateTime(), nullable=True, comment='Soft delete timestamp'),
        sa.ForeignKeyConstraint(['quiz_id'], ['quizzes.id'], ),
        sa.PrimaryKeyConstraint('id')
    )
    
    # Create user_attempts table
    op.create_table('user_attempts',
        sa.Column('user_answer', sa.String(length=1000), nullable=True, comment='User answer'),
        sa.Column('is_correct', sa.Boolean(), nullable=True, comment='Is answer correct'),
        sa.Column('score_earned', sa.Float(), nullable=True, comment='Score earned'),
        sa.Column('feedback_text', sa.String(length=2000), nullable=True, comment='Feedback text'),
        sa.Column('id', sa.String(length=36), nullable=False, comment='User attempt ID'),
        sa.Column('user_id', sa.String(length=36), nullable=False, comment='User ID'),
        sa.Column('quiz_id', sa.String(length=36), nullable=False, comment='Quiz ID'),
        sa.Column('question_id', sa.String(length=36), nullable=False, comment='Question ID'),
        sa.Column('created_at', sa.DateTime(), nullable=False, comment='User attempt created at'),
        sa.Column('updated_at', sa.DateTime(), nullable=False, comment='User attempt updated at'),
        sa.Column('deleted_at', sa.DateTime(), nullable=True, comment='Soft delete timestamp'),
        sa.ForeignKeyConstraint(['question_id'], ['questions.id'], ),
        sa.ForeignKeyConstraint(['quiz_id'], ['quizzes.id'], ),
        sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
        sa.PrimaryKeyConstraint('id')
    )
    
    # Create agent_metrics table
    op.create_table('agent_metrics',
        sa.Column('trace_id', sa.String(length=255), nullable=True, comment='Agent trace ID'),
        sa.Column('event_type', sa.String(length=255), nullable=False, comment='Agent event type'),
        sa.Column('latency_ms', sa.Float(), nullable=True, comment='Agent latency in ms'),
        sa.Column('cost_usd', sa.Float(), nullable=True, comment='Agent cost in USD'),
        sa.Column('accuracy_score', sa.Float(), nullable=True, comment='Agent accuracy score'),
        sa.Column('hallucination_detected', sa.Boolean(), nullable=True, comment='Hallucination detected'),
        sa.Column('id', sa.String(length=36), nullable=False, comment='Agent metric ID'),
        sa.Column('project_id', sa.String(length=36), nullable=False, comment='Project ID'),
        sa.Column('token_usage', sa.JSON(), nullable=True, comment='Token usage'),
        sa.Column('created_at', sa.DateTime(), nullable=False, comment='Agent metric created at'),
        sa.Column('deleted_at', sa.DateTime(), nullable=True, comment='Soft delete timestamp'),
        sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
        sa.PrimaryKeyConstraint('id')
    )
    
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    
    # Drop tables in reverse order
    op.drop_table('agent_metrics')
    op.drop_table('user_attempts')
    op.drop_table('questions')
    op.drop_table('quizzes')
    op.drop_table('materials')
    op.drop_table('projects')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    
    # ### end Alembic commands ###
