"""remove_user_id_from_quiz

Revision ID: 5acc97813619
Revises: a9cab6e8d50d
Create Date: 2026-05-12 14:30:00.000000

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '5acc97813619'
down_revision: Union[str, Sequence[str], None] = 'a9cab6e8d50d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('quizzes', 'user_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('quizzes', sa.Column('user_id', sa.String(length=36), nullable=False))
    # ### end Alembic commands ###
